#! /bin/bash


TYPE="debug"
CPU="AtomicSimpleCPU"
FLAGS=""
START=""

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -o)
    TYPE="opt"
    shift
    ;;
    -d)
    TYPE="debug"
    shift
    ;;
    -A)
    CPU="AtomicSimpleCPU"
    shift
    ;;
    -T)
    CPU="TimingSimpleCPU"
    shift
    ;;
    -M)
    CPU="MinorCPU"
    shift
    ;;
    -O)
    CPU="DerivO3CPU"
    shift
    ;;
    -f)
    FLAGS="--debug-flags=$2"
    shift
    shift
    ;;
    -s)
    START="--debug-start=$2"
    shift
    shift
    ;;
    *)
    POSITIONAL+=("$1")
    shift
    ;;
esac
done

cd $G5

build/RISCV/gem5.$TYPE $FLAGS $START -d $RISCV/logs -re configs/example/riscv/fs_linux.py --kernel=$OUT/bbl --caches --mem-size=128MB --mem-type=DDR4_2400_8x8 --cpu-type=$CPU --disk-image=$OUT/riscv_disk ${POSITIONAL[@]}

# build/RISCV/gem5.$TYPE $FLAGS $START -d $RISCV/logs -re configs/example/riscv/fs_linux.py --kernel=$OUT/diosix --caches --mem-size=2048MB --mem-type=DDR4_2400_8x8 --cpu-type=$CPU --disk-image=$OUT/riscv_disk ${POSITIONAL[@]}
